# Generated by Django 3.0.7 on 2020-06-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logxlift',
            name='repetitions',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logxlift',
            name='sets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logxlift',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=100.1, max_digits=9),
            preserve_default=False,
        ),
    ]
